# Owner: https://t.me/ITSGOLU_OFFICIAL
# Created by: ITSGOLU_OFFICIAL
services:
  - type: web
    name: classplus-token-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
